name: Scrapy Deploy Workflow

on:
  schedule:
    - cron: "0 7,18 * * *"

  pull_request:
    types:
      - closed
    branches: [ master ]
    paths:
      - 'spider/**'
      - '.github/workflows/scrapy.yml'

  workflow_dispatch:


jobs:
  rfi:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python environment
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Run Rfi Spider
        run: |
          cd spider/rfi
          pip install scrapy
          scrapy crawl cn