name: Scrapy Deploy

on:
  schedule:
    - cron: "0 10,23 * * *"

  workflow_dispatch:


jobs:
  rfi:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Rfi Spider
        run: |
          cd spider/rfi
          scrapy crawl cn
